config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  resources :sessions

  resources :courses
  resources :units
  resources :lectures
  
  resources :deliveries
  resources :attachments

  resources :units do
    resources :deliveries do
      resources :attachments
    end
  end

  resources :password_resets
  resources :payments
  resources :users do
    resources :payments
    resources :spots
    resources :deliveries
    resources :units
    resources :lectures
  end

  match '/home',    to: 'static_pages#index',   via: 'get'
  match '/user',    to: 'users#show',           via: 'get'
  match '/edit',    to: 'users#edit',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  post "payments/concept"
  post "courses/unit"
  post "courses/plan"
  get "courses/accordeon"
  get "courses/unit"
  get "courses/positions"

  get ':controller(/:action(/:id))(.:format)'

end

app/models/ability.rb
#encoding: UTF-8
class Ability
  include CanCan::Ability

  def initialize(user)
    current_user ||= User.new
    alias_action :read, :search, :to => :default_actions
    alias_action :edit, :update, :show, :to => :user_actions

    can :user_actions, User, :id => current_user.id

    if current_user.admin?
        can :manage, :all
    else
        
    end

  end

end

app/models/attachment.rb
#encoding: UTF-8
class Attachment < ActiveRecord::Base
	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :lecture

	mount_uploader :file, FileUploader 
	belongs_to :delivery
	belongs_to :lecture

end

app/models/concept.rb
#encoding: UTF-8
class Concept < ActiveRecord::Base
	has_many :payments
end

app/models/course.rb
#encoding: UTF-8
class Course < ActiveRecord::Base

	has_many :spots
	has_many :students, :through => :spots

	has_many :units
	has_many :lectures, through: :units
	validates_presence_of :name

end

app/models/delivery.rb
#encoding: UTF-8
class Delivery < ActiveRecord::Base
	belongs_to :unit
	belongs_to :user
	has_many :attachments, :dependent => :destroy
	accepts_nested_attributes_for :attachments, :allow_destroy => true #, :reject_if => lambda { |a| a[:content].blank? }
	validates_presence_of :unit_id, :user_id
end

app/models/lecture.rb
#encoding: UTF-8
class Lecture < ActiveRecord::Base

	belongs_to :plan
	validates_presence_of :name
	paginates_per 10

end

app/models/payment.rb
#encoding: UTF-8
class Payment < ActiveRecord::Base

	belongs_to :concept
	belongs_to :user

	validates_presence_of :date, :user_id, :concept_id, :quantity

	paginates_per 10

	def amount
		"$#{self.quantity}"
	end

end

app/models/plan.rb
#encoding: UTF-8
class Plan < ActiveRecord::Base

	before_validation :assign_position, on: [ :create ]

	belongs_to :lecture
	belongs_to :unit

	private

	def assign_position
		lectures = self.unit.lectures.count
		self.position = lectures+1
	end

end

app/models/spot.rb
#encoding: UTF-8
class Spot < ActiveRecord::Base

	belongs_to :course
	belongs_to :student, :class_name => 'User'

	validates_uniqueness_of :student_id, :scope => :course_id
	validates_presence_of :student_id, :course_id

end

app/models/unit.rb
#encoding: UTF-8
class Unit < ActiveRecord::Base

	attr_accessor :date, :description, :photo
	
	before_validation :assign_position, on: [ :create ]

	belongs_to :course
	has_many :plans
	has_many :lectures, through: :plans
	has_many :deliveries

	private

	def assign_position
		units = self.course.units.count
		self.position = units+1
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

	before_save :downcase_names
	after_update :crop_user
	after_initialize :titleize_names
	before_create :create_remember_token
	before_save { self.email = email.downcase }

	has_many :spots, :foreign_key => "student_id"
	has_many :courses, through: :spots
	has_many :units, through: :courses
	has_many :lectures, through: :units
	has_many :deliveries, :dependent => :destroy

	has_many :payments, :dependent => :restrict_with_error
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	validates :name, presence: true
	validates :name, length: { maximum: 50 }
	validates :password, length: { minimum: 6 }, :if => :password
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validate :verify_rolls

	has_secure_password

	scope :admins, proc { where(:admin => true) }
	scope :students, proc { where(:student => true) }
	scope :teachers, proc { where(:teacher => true) }

	mount_uploader :photo, PhotoUploader

	def name
		read_attribute(:name).try(:titleize)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
	end

	def crop_user
		photo.recreate_versions! if crop_x.present?
	end

	def verify_rolls
		if !self.student?  && !self.teacher? && !self.admin?
			errors.add(:base, "El usuario debe tener por lo menos un tipo de rol")
		end
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

		def downcase_names
			self.send("#{:name}=", self.send(:name).downcase) if self.send(:name)
		end

		def titleize_names
			self.send("#{:name}=", self.send(:name).titleize) if self.send(:name)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  skip_before_action :require_login, only: [:index]

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Nacho Urquiza"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def head_title(title)
  	html = "<header><h1 class='page-title full-page-title'>#{title}</h1></header>"
  	html.html_safe
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper

	def total_calculate(payments)
		total = 0
		payments.each { |p| total += p.quantity }
		"$#{total}"
	end

end

app/helpers/sessions_helper.rb
# encoding: UTF-8
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Inicia sesión."
    end
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/index.html.erb
<% provide(:title, "Iniciar Sesión") %>
<div class="section row entries bg-primary section-no-margin-bottom">
	<div class="col-lg-8 col-xl-5">
		<div class="row">
			<article class="entry style-grid style-hero hero-md-largest type-post col-md-8 col-lg-12 colheight-sm-1 colheight-md-2 colheight-lg-2 colheight-xl-2">
				
				<div class="ribbon ribbon-pulled ribbon-small ribbon-highlight">
					<a href="blog.html">Bienvenido a Studio Urquiza</a>
				</div>
				<header class="entry-header">
					<h3 class="entry-title">De la Vista Nace el Antojo</h3>
					<div class="entry-meta">
						<span class="entry-date">
						<p>30 años de carrera se traducen en millones de fotos que han sido y son fiel reflejo de la realidad de México, de sus sazones, su gente, coloridos y rincones. Imágenes también del mundo y para el mundo, para todos. Inicia su carrera profesional en 1978, después de realizar estudios en Comunicación, Cine, Periodismo y Fotografía. En 1978 publica sus primeros libros sobre México En el Mundo de la Máscara y Exvotos y Milagros Mexicanos. </p>
						<p>Su encuentro y residencia en Venecia, Italia en 1979, con Ernest Hass, Aldo Ballo, Art Kane y Harold Edgerton, sienta las bases de su formación en las artes visuales y su concepto de arte-imagen. Se muda a Milán para especializarse en fotografía de arquitectura y cocina. Colabora como asistente del reconocido Renato Sala. </p>
						<span>
						<span class="entry-author"><a href="http://www.estudiourquiza.com/" target="_blank">Ignacio Urquiza</a></span>
					</div>
				</header>
				<figure class="entry-thumbnail">
					<a href="single.html" class="overlay overlay-primary"></a>
					<div id="home_slide_show" class="full">
						<!-- backstretch -->
					</div>
				</figure>
			</article>
		</div>
	</div>
	<div class="col-lg-4 col-xl-7" id="login_home">
		<div class="row">
			<article class="entry style-hero type-post col-md-12 col-lg-12 colheight-sm-1 colheight-md-2 colheight-lg-2 colheight-xl-2">
				<div class="ribbon ribbon-pulled ribbon-small ribbon-highlight">
					<a href="blog.html">Inicia Sesión</a>
				</div>
				<header class="entry-header">
					<%= form_for(:session, url: sessions_path) do |f| %>
						<%= f.label :email %>
						<p><%= f.text_field :email, { :class => "form-control" } %></p>
						<p><%= f.label :password, :for => "session_password" %></p>
						<p><%= f.password_field :password, { :class => "form-control" } %></p>
						<div id="sign_in_button">
							<%= f.submit "Iniciar sesión", class: "btn btn-default" %>
						</div>
					<% end %>
					<div class="entry-meta">
						<span>
						¿Eres nuevo? <%= link_to 'Regístrate', new_user_path %> | <%= link_to "¿Olvidaste tu contraseña?" %>
						</span>
					</div>
				</header>
			</article>
		</div>
	</div>
</div>
<script> $(document).ready(static_pages.slideshow()); </script>