config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  resources :sessions

  resources :courses
  resources :units
  resources :lectures
  
  resources :deliveries
  resources :attachments

  resources :units do
    resources :deliveries do
      resources :attachments
    end
  end

  resources :password_resets
  resources :payments
  resources :users do
    resources :payments
    resources :spots
    resources :deliveries
    resources :units
    resources :lectures
  end

  match '/home',    to: 'static_pages#index',   via: 'get'
  match '/user',    to: 'users#show',           via: 'get'
  match '/edit',    to: 'users#edit',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  post "payments/concept"
  post "courses/unit"
  post "courses/plan"
  get "courses/accordeon"
  get "courses/unit"
  get "courses/positions"

  get ':controller(/:action(/:id))(.:format)'

end

app/controllers/courses_controller.rb
#encoding: UTF-8
class CoursesController < ApplicationController

  def index
  	@courses = Course.all.order('id DESC').page(params[:page])
  end

  def show
  	@course = Course.find(params[:id])
  end

  def new
  	@course = Course.new
  end

  def create
  	@course = Course.new(course_params)
  	if @course.save
  		flash[:success] = "Grupo creado exitosamente"
  		redirect_to courses_path
  	else
  		render 'new'
  	end
  end

  def unit
    @course = Course.find(params[:course_id])
    @unit = @course.units.build(title: params[:title] )
    @course.save
  end

  def plan
    @unit = Unit.find(params[:id])
    @lecture = Lecture.new( name: params[:name], content: params[:content], video_url: params[:video_url] )
    @plan = @unit.plans.build({ lecture_id: @lecture.id }) if @lecture.save
    @unit.save
  end

  def update
  	@course = Course.find(params[:id])
  	if @course.update_attributes(course_params)
  		flash[:success] = "Grupo creado exitosamente"
  		redirect_to course_path(@course)
  	else
  		render 'edit'
  	end
  end

  def edit
  	@course = Course.find(params[:id])
  end

  def accordeon
    @unit = Unit.find(params[:id])
  end

  def positions
    positions = params[:positions]
    @course = Course.find(params[:id])
    positions.each_with_index do |id,index|
      unit=@course.units.find_by_id(id)
      if unit
        unit.position=index
        unit.save
      end
    end
  end

  private

  def course_params
  	params.require(:course).permit(:name, :level)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/views/courses/_actions.htmls.erb
<% if current_user.student? %>
	<button class="btn btn-primary right">
		<i class="icon-cogs icon"></i>Entregar tarea
	</button>
<% else %>

<% end %>

app/views/courses/_form.html.erb
<div class="row">
	<div class="col-md-3 col-md-offset-3">
		<%= simple_form_for @course do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<%= f.input :level, label: "Nivel", :include_blank => true, collection: [['Principiante','Principiante'],['Avanzado','Avanzado']] %>
		<p><%= f.input :name, label: "Nombre del curso" %></p>
		<% if params[:action]=='new' %>
			<p><%= f.submit "Crear Pago", class: "btn btn-default" %></p>
		<% else %>
			<p><%= f.submit "Guardar Pago", class: "btn btn-default" %></p>
		<% end %>
		<% end %>
	</div>
</div>

app/views/courses/_index.html.erb
<% if @courses.empty? %>
	<p>- No hay grupos - </p>
<% else %>
	<table class="table table-striped tablesorter">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Nivel</th>
				<th>Editar</th>
				<th>Eliminar</th>
			</tr>
		</thead>
		<tbody>
			<% @courses.each do |course| %>
				<tr>
					<td><%= link_to course.name, course_path(course) %></td>
					<td><%= link_to course.level, course_path(course) %></td>
					<td><%= link_to "Editar", edit_course_path(course), :class => "btn btn-info btn-xs" %></td>
					<td><%= link_to "Eliminar", course_path(course) , :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Estás seguro de borrar este curso?' } %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>

<%= paginate @courses %>

app/views/courses/_plan.html.erb
<% lecture = lecture || @lecture %>
<% object = object || @unit  %>
<% index = index || object.lectures.count %>
<tr id="unit_<%= object.id %>_plan_<%= lecture.id %>" class="unit_plan">
	<td valign="middle" class="relative">
		<div class="arrow_asc">
			<a href="javascript:void(0);" class="asc left icon icon-chevron-up" data-id="<%= lecture.id %>" data-position="<%= index %>" onClick="course_actions.reorder(event);"></a>
		</div>
		<div class="arrow_desc">
			<a href="javascript:void(0);" class="left icon icon-chevron-down" data-id="<%= lecture.id %>" data-position="<%= index %>" onClick="course_actions.reorder(event);"></a>
		</div>
	</td>
	<td valign="middle">
		<!-- Button trigger video modal -->
		<%= link_to lecture.name, lecture_path(lecture) %>
	</td>
	<td class="aligncenter" valign="middle">
		<div data-toggle="modal" data-target="#video_lecture_modal">
			<%= image_tag "http://img.youtube.com/vi/#{lecture.video_url}/#{rand(1..3)}.jpg", :class => "pointer_cursor without_margin", data: { :lecture => lecture.name, video: lecture.video_url }, onClick: "course_actions.open_modal_video(event);" %>
		</div>
	</td>
	<td class="aligncenter" valign="middle">
		<%= link_to "Editar", edit_lecture_path(lecture), :class => "btn btn-info btn-xs" %>
	</td>
	<td class="aligncenter" valign="middle">
		<%= link_to "Borrar", lecture_path(lecture), :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Estás seguro de borrar este curso?' } %>
	</td>
</tr>

app/views/courses/_unit.html.erb
<% object = object || @unit %>
<% index = index || (@course.units.count-1) %>
<div class="panel panel-primary panel_unit left relative panel_unit_<%= object.id %>" id="panel_unit_<%= object.position %>" data-position="<%= object.id %>">
	<div class="panel-heading relative <% if params[:action]!='show' %>unit_new<% end %>">
		<h4 class="panel-title">
			<div class="container_reorder_arrows absolute">
				<div class="absolute container_input_position">
					<input class="form-control input_position" placeholder="<%= object.position+1 %>" type="text" onkeyup="course_actions.keyUp(event);" data-id="<%= object.position %>">
				</div>
				<div class="arrow_asc absolute">
					<a href="javascript:void(0);" class="asc left icon icon-chevron-up" data-id="<%= object.position %>" data-position="<%= object.id %>" onClick="course_actions.reorder(event);"></a>
				</div>
				<div class="arrow_desc absolute">
					<a href="javascript:void(0);" class="left icon icon-chevron-down" data-id="<%= object.position %>" data-position="<%= object.id %>" onClick="course_actions.reorder(event);"></a>
				</div>
			</div>
			<div class="container_lecture_actions reorder_units absolute">
				<%= link_to unit_path(object) , :class => "btn link_icon right btn-xs btn-danger", method: :delete, data: { confirm: 'Estás seguro de borrar este curso?' } do %>
					<i class="icon icon-remove"></i>Eliminar
				<% end %>
				<%= link_to unit_path(object) , :class => "btn link_icon right btn-xs btn-info" do %>
					<i class="icon icon-eye-open"></i>Ver
				<% end %>
			</div>
			<a class="accordion-toggle panel_title_lecture accordion accordion_unit" data-toggle="collapse" data-parent="#accordion" href="#unit_detail_<%= object.id %>" data-unit="<%= object.id %>" data-open="true" onClick="course_actions.loadUnit(event);">
				<%= object.title %>
			</a>
		</h4>
	</div>
	<div id="unit_detail_<%= object.id %>" class="panel-collapse collapse" style="height: 0px;">
		<div class="remove_preloader_content">
			<img src="/assets/preloader.GIF" alt="">
		</div>
	</div>
</div>

app/views/courses/accordeon.html.erb
<% object = object || @unit %>
<% index = index || (@unit.course.units.count-1) %>
<div id="accordeon_unit_content">
	<div class="panel-body table-responsive">
		<a href="#" class="link_icon btn btn-default right">
			<i class="icon icon-list-ol"></i> Reordenar Clases
		</a>
		<button href="#" class="link_icon btn btn-default right" data-toggle="modal" data-target="#new_lecture_modal" onClick="$('#new_unit_id').val('<%= object.id %>');">
		<i class="icon icon-file-alt"></i> Nueva Clase
		</button>
		<table class="table table-hover table-bordered tablesorter">
			<thead>
				<tr>
					<th>Posición</th>
					<th>Clase</th>
					<th class="aligncenter">Video</th>
					<th class="aligncenter">Editar</th>
					<th class="aligncenter">Borrar</th>
				</tr>
			</thead>
			<tbody id="container_lectures_unit_<%= object.id %>">
				<% object.lectures.order("position ASC").each_with_index do |lecture, index| %>
				<%= render "courses/plan", object: object, lecture: lecture, index: index %>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/courses/edit.html.erb
<%= head_title("Editar Curso") %>
<%= render "courses/form" %>

app/views/courses/index.html.erb
<div class="content bg-base section">
	
	<div class="ribbon ribbon-highlight">
		<ol class="breadcrumb ribbon-inner">
			<li><a href="/">Home</a></li>
		</ol>
	</div>

	<%= head_title("Detalle de Cursos") %>

	<div class="row style-single">
		<nav class="col-sm-3 sidenav">
			<div class="panel-group">
				<div class="panel panel-primary">
					<div class="panel-heading">
						<h4 class="panel-title">
						<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#user_profile">Cursos</a>
						</h4>
					</div>
				</div>
			</div>
		</nav>
		<div class="col-sm-9 entry-content">
			<h2>
				Detalle
				<a class="btn btn-info right" href="/courses/new">Nuevo Curso</a>
			</h2>
			<div class="row">
				<%= render 'courses/index' %>
			</div>
		</div>
	</div>
</div>

app/views/courses/new.html.erb
<%= head_title("Nuevo Curso") %>
<%= render "courses/form" %>

app/views/courses/plan.js.erb
<% if @lecture.valid? %>
	$("#errors_lectures_unit_<%= @unit.id %>, #error_explanation").html("");
	$("#new_lecture_modal").modal("hide");
	$(".reset_new_unit").val("");
	$("#container_lectures_unit_<%= @unit.id %>").append("<%= escape_javascript(render('plan')) %>");
<% else %>
	$("#errors_lectures_new_unit").html("<%= escape_javascript(render('shared/error_messages', object: @lecture)) %>");
<% end %>

app/views/courses/show.html.erb
<% provide(:title, "Curso #{@course.name}") %>
<div id="refresh_content">
	<%= head_title("Curso #{@course.name}") %>
	<h2 id="unit_details">
	Unidades del Curso
	<button class="reorder_units btn btn-danger right" onClick='course_actions.disabled_reorder();'>Cancelar</button>
	<button class="reorder_units btn btn-success right" onClick="course_actions.save();">Guardar Cambios</button>
	<button class="reorder_units btn btn-primary right" onClick="course_actions.enabled_reorder();" id="reorder_units">
	<i class="icon-cogs icon"></i>Administrar</button>
	<button class="reorder_units btn btn-default right" data-toggle="modal" id="new_unit" data-target="#new_unit_modal">
	<i class="icon-folder-open-alt icon"></i>Nueva Unidad
	</button>
	</h2>
	<div class="row">
		<div class="panel panel-primary" id="container_units" data-course="<%= @course.id %>">
			<% @course.units.order("position ASC").each_with_index do |unit, index| %>
			<%= render 'courses/unit', object: unit, index: index %>
			<% end %>
		</div>
	</div>
</div>
<!-- modals -->
<!-- new unit modal -->
<!-- Modal -->
<div class="modal fade" id="new_unit_modal" tabindex="-1" role="dialog" aria-labelledby="newCourseUnit" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="newCourseUnit"><b>Curso: <%= @course.name %></b> | Nueva Unidad</h4>
			</div>
			<%= form_tag( { :controller => :courses, :action => :unit }, { :remote => true, :id => 'course_unit_form' } ) do %>
			<div class="modal-body">
				<%= number_field_tag "course_id", @course.id, :hidden => true %>
				<%= text_field_tag "title", nil, :class => "form-control", placeholder: "Escribe el nombre de la nueva unidad.", id: "new_unit_field_name" %>
			</div>
			<div class="modal-footer">
				<%= submit_tag "Crear Unidad", :class => "btn btn-success" %>
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
			</div>
			<% end %>
		</div>
	</div>
</div>
<!-- end new unit modal -->
<!-- Dynamic Video Modal -->
<div class="modal fade" id="video_lecture_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Cerrar</span></button>
				<h4 class="modal-title" id="myModalLabel">
				<b><span id="video_open_modal_name"></span></b> | Video de clase</h4>
			</div>
			<div class="modal-body" id="container_open_video_modal">
				<!-- render iframe video -->
			</div>
		</div>
	</div>
</div>
<!-- close dynamic video modal  -->
<!-- add new unit modal -->
<!-- new unit modal -->
<div class="modal fade" id="new_lecture_modal" tabindex="-1" role="dialog" aria-labelledby="newUnitLecture" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="newUnitLecture"><b>Unidad: <span id="unit_title"></span></b> | Nueva Clase</h4>
			</div>
			<%= form_tag({ :controller => :courses, :action => :plan }, { :remote => true }) do %>
			<div class="modal-body">
				<div id="errors_lectures_new_unit"></div>
				<%= number_field_tag "id", nil, :hidden => true, id: "new_unit_id" %>
				<p><%= text_field_tag "name", nil, :class => "reset_new_unit form-control", placeholder: "Escribe el nombre de la nueva clase." %></p>
				<iframe width="100%" height="315" src="//www.youtube.com/embed/" frameborder="0" allowfullscreen id="video_new_unit_url"></iframe>
				<p><%= text_field_tag "video_url", nil, :class => "reset_new_unit form-control", placeholder: "Url de video de clase.", :onkeyup => "course_actions.load_video(event);" %></p>
				<p><%= text_area_tag "content", nil, :class => "reset_new_unit form-control wysihtml5", placeholder: "Contenido de la clase." %></p>
			</div>
			<div class="modal-footer">
				<%= submit_tag "Crear Clase", :class => "btn btn-success" %>
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
			</div>
			<% end %>
		</div>
	</div>
</div>
<!-- end unit modal -->
<!-- modals -->

app/views/courses/unit.js.erb
$("#new_unit_modal").modal("hide");
$("#container_units").append("<%= escape_javascript(render('unit')) %>");
$("body, html").animate({scrollTop:$("#panel_unit_<%= @unit.position %>").offset().top},900,function(){
	$("#new_unit_field_name").val("");
	$('.unit_new').removeClass('unit_new');
});