config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  resources :sessions

  resources :courses
  resources :units
  resources :lectures
  
  resources :deliveries
  resources :attachments

  resources :units do
    resources :deliveries do
      resources :attachments
    end
  end

  resources :password_resets
  resources :payments
  resources :users do
    resources :payments
    resources :spots
    resources :deliveries
    resources :units
    resources :lectures
  end

  match '/home',    to: 'static_pages#index',   via: 'get'
  match '/user',    to: 'users#show',           via: 'get'
  match '/edit',    to: 'users#edit',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  post "payments/concept"
  post "courses/unit"
  post "courses/plan"
  get "courses/accordeon"
  get "courses/unit"
  get "courses/positions"

  get ':controller(/:action(/:id))(.:format)'

end

app/models/unit.rb
#encoding: UTF-8
class Unit < ActiveRecord::Base

	attr_accessor :date, :description, :photo
	
	before_validation :assign_position, on: [ :create ]

	belongs_to :course
	has_many :plans
	has_many :lectures, through: :plans
	has_many :deliveries

	private

	def assign_position
		units = self.course.units.count
		self.position = units+1
	end

end

app/controllers/units_controller.rb
#encoding: UTF-8
class UnitsController < ApplicationController

  def index
  	@units = Unit.all
  end

  def show
  	@unit = Unit.find(params[:id])
    @delivery = current_user.deliveries.build
    @delivery.unit_id = @unit.id
    # 3.times { @delivery.attachments.build }
    @delivery.attachments.build
    render "units/show", :layout => false
  end

  def new
  	@unit = Unit.new
  end

  def edit
  	@unit = Unit.find(params[:id])
  end

  def destroy
    Unit.find(params[:id]).destroy
    redirect_to :back
  end

end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_actions.html.erb
<% if current_user.student? %>
<button class="btn btn-default right" data-toggle="modal" data-target="#new_delivery">
<i class="icon-cogs icon"></i>Entregar tarea modal
</button>
<%= link_to "Entregar tarea", new_unit_delivery_path(@unit), :class => "btn btn-default right" %>
<!-- deliveries modal -->
<!-- Modal -->
<div class="modal fade" id="new_delivery" tabindex="-1" role="dialog" aria-labelledby="newUnitDelivery" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title" id="newUnitDelivery"><b><%= @unit.title %></b> | Nueva entrega</h4>
			</div>
			<%= simple_form_for @delivery, remote: true  do |d| %>
			<div class="modal-body" id="container_deliveries">
				<%= render 'deliveries/modal', object: d %>
				<div id="drop_zone">
					Arrastra tus documentos e imagenes
				</div>
				<input type="file" id="unit_attachments" name="unit_attachments" multiple="true" onChange="attachments.handleFileSelect(event);">
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				<%= d.submit "Guardar entrega", :class => "btn btn-primary" %>
			</div>
			<% end %>
		</div>
	</div>
</div>
<!-- deliveries modal -->
<% else %>
<% end %>

app/views/units/edit.html.erb
<h1>Units#edit</h1>
<p>Find me in app/views/units/edit.html.erb</p>

app/views/units/index.html.erb
<h1>Units#index</h1>
<p>Find me in app/views/units/index.html.erb</p>

app/views/units/new.html.erb
<div class="ribbon ribbon-highlight">
  <ol class="breadcrumb ribbon-inner">
    <li><a href="/">Administrador</a></li>
    <li><a href="3">Museo Amparo</a></li>
    <li><a href="3">Exposiciones</a></li>
    <li class="active">Nuevo</li>
  </ol>
</div>
<header class="page-header">
  <h1 class="page-title full-page-title"><b>Museo Amparo</b> | Nueva exposición</h1>
</header>
<div class="col-md-8 col-md-offset-2">
  <%= simple_form_for @unit do |f| %>
  <p><%= f.input "title", as: "string", label: "Nombre de la exposición" %>
  </p>
  <div id="container_image_url">
    <img src="/assets/default/user/default.png" id="image_url" alt="">
  </div>
  <div id="unit_photo_input" class="btn-default">
    <p><%= f.input :photo, as: "file", label:"Seleccionar foto de portada" %></p>
  </div>
  <div class="col-md-6" style="padding: 0;">
    <div class="selector_fecha">
      <%= f.input "date", as: "date", label: "Fecha de inicio", :order => [:day, :month, :year], :include_blank => true, :start_year => Date.today.year, :end_year =>Date.today.year-1, :input_html => { :class => 'date_selector' }  %>
    </div>
  </div>
  <div class="col-md-6" style="padding: 0;">
    <div class="selector_fecha">
      <%= f.input "date", as: "date", label: "Fecha final", :order => [:day, :month, :year], :include_blank => true, :start_year => Date.today.year, :end_year =>Date.today.year-1, :input_html => { :class => 'date_selector' }  %>
    </div>
  </div>
  <div class="selector_fecha">
    <p>
      <%= check_box_tag 'eula', 'accepted', false %>
      <%= label_tag :eula, 'Permanente?', :style => "display:inline;" %>
    </p>
  </div>
  <p><%= f.input "description", as: "text", label: "Descripción", :input_html => { :class => "wysihtml5" }  %>
  </p>
  <p><%= f.submit "Crear Exposición", class: "form-control btn btn-default" %></p>
  <% end %>
</div>

app/views/units/show.html.erb
<% provide(:title, "Unidad: #{@unit.title}") %>
<div id="refresh_content">
	<%= head_title("Unidad: #{@unit.title}") %>
	<h2>Detalles de la Unidad</h2>
	<%= render "/units/actions" %>
	<div class="row">
		<ul class="nav">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th><span class="glyphicon glyphicon-book"></span></th>
						<th><%= link_to @unit.title, user_unit_path(current_user, @unit), remote: true, class: "remote" %></th>
					</tr>
				</thead>
				<tbody>
					<% @unit.lectures.each do |lecture| %>
					<tr>
						<td>
							<span class="glyphicon glyphicon-list-alt"></span>
						</td>
						<td>
							<%= link_to lecture.name, user_lecture_path(current_user, lecture), class: "remote" %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</ul>
	</div>
</div>