config/routes.rb
Rails.application.routes.draw do

  root "static_pages#index"

  resources :sessions

  resources :courses
  resources :units
  resources :lectures
  
  resources :deliveries
  resources :attachments

  resources :units do
    resources :deliveries do
      resources :attachments
    end
  end

  resources :password_resets
  resources :payments
  resources :users do
    resources :payments
    resources :spots
    resources :deliveries
    resources :units
    resources :lectures
  end

  match '/home',    to: 'static_pages#index',   via: 'get'
  match '/user',    to: 'users#show',           via: 'get'
  match '/edit',    to: 'users#edit',           via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  post "payments/concept"
  post "courses/unit"
  post "courses/plan"
  get "courses/accordeon"
  get "courses/unit"
  get "courses/positions"

  get ':controller(/:action(/:id))(.:format)'

end

app/models/ability.rb
#encoding: UTF-8
class Ability
  include CanCan::Ability

  def initialize(user)
    current_user ||= User.new
    alias_action :read, :search, :to => :default_actions
    alias_action :edit, :update, :show, :to => :user_actions

    can :user_actions, User, :id => current_user.id

    if current_user.admin?
        can :manage, :all
    else
        
    end

  end

end

app/models/attachment.rb
#encoding: UTF-8
class Attachment < ActiveRecord::Base
	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :lecture

	mount_uploader :file, FileUploader 
	belongs_to :delivery
	belongs_to :lecture

end

app/models/concept.rb
#encoding: UTF-8
class Concept < ActiveRecord::Base
	has_many :payments
end

app/models/course.rb
#encoding: UTF-8
class Course < ActiveRecord::Base

	has_many :spots
	has_many :students, :through => :spots

	has_many :units
	has_many :lectures, through: :units
	validates_presence_of :name

end

app/models/delivery.rb
#encoding: UTF-8
class Delivery < ActiveRecord::Base
	belongs_to :unit
	belongs_to :user
	has_many :attachments, :dependent => :destroy
	accepts_nested_attributes_for :attachments, :allow_destroy => true #, :reject_if => lambda { |a| a[:content].blank? }
	validates_presence_of :unit_id, :user_id
end

app/models/lecture.rb
#encoding: UTF-8
class Lecture < ActiveRecord::Base

	belongs_to :plan
	validates_presence_of :name
	paginates_per 10

end

app/models/payment.rb
#encoding: UTF-8
class Payment < ActiveRecord::Base

	belongs_to :concept
	belongs_to :user

	validates_presence_of :date, :user_id, :concept_id, :quantity

	paginates_per 10

	def amount
		"$#{self.quantity}"
	end

end

app/models/plan.rb
#encoding: UTF-8
class Plan < ActiveRecord::Base

	before_validation :assign_position, on: [ :create ]

	belongs_to :lecture
	belongs_to :unit

	private

	def assign_position
		lectures = self.unit.lectures.count
		self.position = lectures+1
	end

end

app/models/spot.rb
#encoding: UTF-8
class Spot < ActiveRecord::Base

	belongs_to :course
	belongs_to :student, :class_name => 'User'

	validates_uniqueness_of :student_id, :scope => :course_id
	validates_presence_of :student_id, :course_id

end

app/models/unit.rb
#encoding: UTF-8
class Unit < ActiveRecord::Base

	attr_accessor :date, :description, :photo
	
	before_validation :assign_position, on: [ :create ]

	belongs_to :course
	has_many :plans
	has_many :lectures, through: :plans
	has_many :deliveries

	private

	def assign_position
		units = self.course.units.count
		self.position = units+1
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

	before_save :downcase_names
	after_update :crop_user
	after_initialize :titleize_names
	before_create :create_remember_token
	before_save { self.email = email.downcase }

	has_many :spots, :foreign_key => "student_id"
	has_many :courses, through: :spots
	has_many :units, through: :courses
	has_many :lectures, through: :units
	has_many :deliveries, :dependent => :destroy

	has_many :payments, :dependent => :restrict_with_error
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	validates :name, presence: true
	validates :name, length: { maximum: 50 }
	validates :password, length: { minimum: 6 }, :if => :password
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validate :verify_rolls

	has_secure_password

	scope :admins, proc { where(:admin => true) }
	scope :students, proc { where(:student => true) }
	scope :teachers, proc { where(:teacher => true) }

	mount_uploader :photo, PhotoUploader

	def name
		read_attribute(:name).try(:titleize)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
    	Digest::SHA1.hexdigest(token.to_s)
	end

	def crop_user
		photo.recreate_versions! if crop_x.present?
	end

	def verify_rolls
		if !self.student?  && !self.teacher? && !self.admin?
			errors.add(:base, "El usuario debe tener por lo menos un tipo de rol")
		end
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end

		def downcase_names
			self.send("#{:name}=", self.send(:name).downcase) if self.send(:name)
		end

		def titleize_names
			self.send("#{:name}=", self.send(:name).titleize) if self.send(:name)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Nacho Urquiza"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def head_title(title)
  	html = "<header><h1 class='page-title full-page-title'>#{title}</h1></header>"
  	html.html_safe
  end

end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/helpers/deliveries_helper.rb
module DeliveriesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper

	def total_calculate(payments)
		total = 0
		payments.each { |p| total += p.quantity }
		"$#{total}"
	end

end

app/helpers/sessions_helper.rb
# encoding: UTF-8
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Inicia sesión."
    end
  end

  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    current_user.update_attribute(:remember_token, User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_breadcrumb.html.erb
<div class="ribbon ribbon-highlight">
	<ol class="breadcrumb ribbon-inner">
		<li><a href="#">Home</a></li>
		<li class="active">Review Archive</li>
	</ol>
</div>

app/views/layouts/_errors_modals.html.erb
<div class="modal fade" id="attachment_error" tabindex="-1" role="dialog" aria-labelledby="attachmentErrors" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header background_base">
				<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
				</button>
				<h4 class="modal-title" id="attachmentErrors">Browser Inválido</h4>
			</div>
			<div class="modal-body aligncenter">
				<p>Para poder subir archivos actualiza tu navegador.</p>
				<p>Tu browser no soporta la función para adjuntar archivos.</p>
			</div>
			<div class="modal-footer">
				<a type="button" class="btn btn-default" href="http://www.google.com.mx/intl/es-419/chrome/" target="_blank">Actualizar Browser</a>
				<button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<h1 class="sr-only">Summarize</h1>
<nav id="header" class="header-navbar" role="navigation">
  <div class="header-navbar-inner container">
    <div id="brand" class="navbar-brand">
      <a href="/" rel="bookmark">
        <img src="/assets/light-logo.png" data-src="/assets/light-logo.png" data-src-retina="/assets/logo-retina.png" width="244" height="56" alt="">
        <noscript>
        <img src="/assets/light-logo.png" alt="">
        </noscript>
      </a>
    </div>
    <ul class="nav nav-pages hidden-xs">
      <li><a href="#">D0A3</a></li>
      <li><a href="#">Contacto</a></li>
      <li><a href="#">Términos &amp; Condiciones</a></li>
      <li><a href="#">Aviso de Privacidad</a></li>
      <% if !current_user %>
      <li><%= link_to "Iniciar Sesión", signin_path %></li>
      <% end %>
    </ul>
    <% if current_user %>
    <ul class="nav nav-icons">
      <li>
        <a class="accordion-toggle btn-icon" data-toggle="collapse" data-parent="#accordion" href="#container_sessions_actions">
          <span class="glyphicon glyphicon-cog"></span>
        </a>
      </li>
      <div id="container_sessions_actions" class="panel-collapse collapse right relative" style="height: 0px;">
        <ul>
          <%= link_to user_path(current_user) do %>
          <li>Mi perfil</li>
          <% end %>
          <%= link_to edit_user_path(current_user) do %>
          <li>Editar perfil</li>
          <% end %>
          <%= link_to edit_password_reset_path(current_user) do %>
          <li>Cambiar contraseña</li>
          <% end %>
          <%= link_to signout_path, :method => "delete" do %><li>Cerrar Sesión</li><% end %>
        </ul>
      </div>
    </ul>
    <% end %>
    <ul class="nav nav-icons">
      <li>
        <a href="#" class="btn-icon" data-toggle=".header-navbar-inner" data-toggle-class="search-toggled-in">
          <span class="search-toggled-out-icon glyphicon glyphicon-search"></span>
          <span class="search-toggled-in-icon glyphicon glyphicon-remove"></span>
        </a>
      </li>
    </ul>
    <div class="search-wrapper js-stoppropagation">
      <div class="search-wrapper-inner">
        <form>
          <input type="text" value="" placeholder="Buscar ... ">
          <button class="btn-icon" type="submit"><span class="glyphicon glyphicon-search"></span></button>
        </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_menu.html.erb
<% if current_user %>
	<% if current_user.admin? %>
		<%= render "menus/admin_menu" %>
	<% end %>
	<% if current_user.student? %>
		<%= render "menus/student_menu" %>
	<% end %>
	<% if current_user.teacher? %>
		<%= render "menus/teacher_menu" %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>   <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>      <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>      <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
	<!--<![endif]-->
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Lato:300,400,700,400italic,700italic|Droid+Serif' rel='stylesheet' type='text/css'>
			<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
			<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
			<%= csrf_meta_tags %>
		</head>
		<body>
			<!-- header -->
			<%= render 'layouts/header' %>
			<!-- header -->
			<div id="blog_wrapper">
				<div id="main" class="container">
					<div id="flash_messages">
						<% flash.each do |key, value| %>
							<%= content_tag(:div, value, class: "alert alert-#{key}") %>
						<% end %>
					</div>
					<div class="content bg-base section">
						<%= render "layouts/breadcrumb" %>
						<div class="row style-single">
							<nav class="col-sm-3 sidenav">
								<%= render "layouts/menu" %>
							</nav>
							<!-- yield -->
							<div class="col-sm-9 entry-content" id="ajax_escape">
								<%= yield %>
							</div>
							<!-- yield -->
						</div>
					</div>
				</div>
			</div>
			<!-- init modal errors notifications -->
			<%= render "layouts/errors_modals" %>
			<!-- end modal errors notifications -->
		</body>
	</html>

app/views/menus/_student_menu.html.erb
<div class="panel-group" id="user_menu">
	<div class="panel panel-primary">
		<!-- init profile -->
		<div class="panel-heading">
			<h4 class="panel-title">
			<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#user_profile">Perfil</a>
			</h4>
		</div>
		<div id="user_profile" class="panel-collapse collapse" style="height: 0px;">
			<div class="panel-body">
				<ul class="nav">
					<li>
						<% if current_user.photo_url.include?('/default/') %>
						<%= image_tag current_user.photo_url.to_s, id: 'image_url' %>
						<% else %>
						<%= image_tag current_user.photo_url(:thumb).to_s, :class => "profile_thumb" %>
						<% end %>
					</li>
					<li><a href="#"><%= current_user.name %></a></li>
					<li><a href="#"><%= current_user.email %></a></li>
					<li><a href="#info_user">Perfil</a></li>
					<li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
					<li><%= link_to "Cambiar contraseña", edit_password_reset_path(current_user) %></li>
				</ul>
			</div>
		</div>
		<!-- end profile -->
		<!-- init courses -->
		<% if !current_user.courses.empty? %>
		<div class="panel-heading">
			<h4 class="panel-title">
			<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#users_courses">Cursos</a>
			</h4>
		</div>
		<div id="users_courses" class="panel-collapse collapse" style="height: 0px;">
			<div class="panel-body">
				<% current_user.courses.each do |course| %>
				<ul class="nav">
					<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#course_units">
						<div class="panel-heading">
							<h4 class="panel-title"><%= course.name %></h4>
						</div>
					</a>
				</ul>
				<div id="course_units" class="panel-collapse collapse" style="height: 0px;">
					<div class="panel-body">
						<ul class="nav">
							<% course.units.each do |unit| %>
							<table class="table table-hover table-bordered">
								<thead>
									<tr>
										<th><span class="glyphicon glyphicon-book"></span></th>
										<th><%= link_to unit.title, user_unit_path(current_user, unit), remote: true, class: "remote" %></th>
									</tr>
								</thead>
								<tbody>
									<% unit.lectures.each do |lecture| %>
									<tr>
										<td><span class="glyphicon glyphicon-list-alt"></span></td>
										<td><%= link_to lecture.name, user_lecture_path(current_user, lecture), class: "remote" %></td>
									</tr>
									<% end %>
								</tbody>
							</table>
							<% end %>
						</ul>
					</div>
				</div>
				<% end %>
			</div>
		</div>
		<% end %>
		<!-- end courses -->
		<!-- init payments -->
		<div class="panel-heading">
			<h4 class="panel-title">
			<%= link_to "Pagos", user_payments_path(current_user) %>
			</h4>
		</div>
		<!-- end payments -->
	</div>
</div>

app/views/menus/_users_nav.html.erb
<% if current_user.admin? %>
	<%= render "menus/admin_menu" %>
<% end %>
<% if current_user.student? %>
	<%= render "menus/student_menu" %>
<% end %>
<% if current_user.teacher? %>
	<%= render "menus/teacher_menu" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      La forma contiene <%= object.errors.count %>
      <%  if object.errors.count == 1 %>error<% else %>errores<%end%>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>